version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 1000:80
    environment:
        - PGADMIN_DEFAULT_EMAIL=christian.mahardhika@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=Jancuk#1
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
    ports: 
        - 5432:5432

volumes:
  postgres_data: