version: '3.7'

services:
  apps:
    image: ghcr.io/christianmahardhika/mini-be-services-ecommerce:latest
    ports:
      - "55501:55501"
    container_name: mini-be-services-ecommerce-app
    env_file:
      - fileName: .env
        filePath: .
    depends_on:
      db:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 1000:80
    environment:
        - PGADMIN_DEFAULT_EMAIL=christian.mahardhika@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=Telkomsel#1
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=ecommerce
    ports: 
        - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: